import os

#Helper functions

def getSources(rootPath):
    sources = []
    for dir in getAllSubdirs(rootPath, []):
        sources += Glob(dir)
    return sources

def getAllSubdirs(rootPath, dirs):
    dirs.append(os.path.join(rootPath, "*.cpp"))
    for name in os.listdir(rootPath):
        if os.path.isdir(os.path.join(rootPath, name)) and name[0] != '.':
            getAllSubdirs(os.path.join(rootPath, name), dirs)
    return dirs

# SCons config
platform = ARGUMENTS.get('platform', 'linux')

includeDir = ["#/include", "../src/cricket/include", "../src/cricketsfml/include", "../src/game/include"]
libDir = "#/libs/" + platform
srcDir = "src"
if platform == 'linux':
    libs = ['sfml-graphics-s', 'sfml-window-s', 'sfml-system-s', 'GLEW', 'pthread', 'jpeg', 'freetype', 'Xrandr', 'rt']
else:    
    libs = ['sfml-graphics', 'sfml-window', 'sfml-system']

env = Environment(
    LIBDIR = libDir,
    CPPPATH = includeDir,
    LIBPATH = libDir,
    LIBS = libs
)

if platform == 'linux':
    env.Append(CCFLAGS='-DSFML_STATIC')
# Since we are in bin directory, path should be ../src
sources = getSources('../src/cricket')
sources += getSources('../src/cricketsfml')
sources += getSources('../src/game')
env.Program('asteroids', sources)
